# Generated by Django 5.2.3 on 2025-06-21 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="seller",
            name="quality",
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
    ]
