# Generated by Django 5.2.3 on 2025-06-21 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Seller",
        ),
    ]
